### ISSUE TITLE
求部署指教

### ISSUE THREAD

**Issue by GuiZhouAndroid** [KBdog/kbcomic#1]
想学习您的项目，但是前端怎么对接呀

**Comment by KBdog** [comment]
> 想学习您的项目，但是前端怎么对接呀

本地建文件夹，先用爬虫工具把漫画爬下来放到文件夹里，kbcomic这个服务的本地漫画文件夹路径映射成刚刚创建好的那个，数据库也根据给出的sql创建好几个表，改一下配置文件就可以部署了，这个服务的前端在magnet-system-web里，可以用token登录上去或自行本地部署magnet-system连数据库登录，找到漫画爬虫的页面后就可以测试了
